// This file was generated by counterfeiter
package fakes

import (
	"net/http"
	"sync"

	"github.com/cloudfoundry-incubator/cli-plugin-repo/server"
)

type FakeServerHandles struct {
	ListPluginsStub        func(w http.ResponseWriter, r *http.Request)
	listPluginsMutex       sync.RWMutex
	listPluginsArgsForCall []struct {
		w http.ResponseWriter
		r *http.Request
	}
}

func (fake *FakeServerHandles) ListPlugins(w http.ResponseWriter, r *http.Request) {
	fake.listPluginsMutex.Lock()
	defer fake.listPluginsMutex.Unlock()
	fake.listPluginsArgsForCall = append(fake.listPluginsArgsForCall, struct {
		w http.ResponseWriter
		r *http.Request
	}{w, r})
	if fake.ListPluginsStub != nil {
		fake.ListPluginsStub(w, r)
	}
}

func (fake *FakeServerHandles) ListPluginsCallCount() int {
	fake.listPluginsMutex.RLock()
	defer fake.listPluginsMutex.RUnlock()
	return len(fake.listPluginsArgsForCall)
}

func (fake *FakeServerHandles) ListPluginsArgsForCall(i int) (http.ResponseWriter, *http.Request) {
	fake.listPluginsMutex.RLock()
	defer fake.listPluginsMutex.RUnlock()
	return fake.listPluginsArgsForCall[i].w, fake.listPluginsArgsForCall[i].r
}

var _ server.ServerHandles = new(FakeServerHandles)
