---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: cli-plugin-repo
  type: git
  source:
    uri: https://github.com/cloudfoundry/cli-plugin-repo
    branch: master

- name: cli-plugin-repo-pws
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: ((cli-pws-username))
    password: ((cli-pws-password))
    organization: ((cli-pws-organization))
    space: ((cli-pws-space))
    skip_cert_check: false

- name: cf-cli-tracker
  type: tracker
  source:
    token: ((cf-cli-public-tracker-token))
    project_id: ((cf-cli-public-tracker-project-id))
    tracker_url: https://www.pivotaltracker.com

- name: slack-alert
  type: slack-notification
  source:
    url: ((slack-webhook-url))

jobs:
- name: test
  plan:
  - get: cli-plugin-repo
    trigger: true
  - task: test
    file: cli-plugin-repo/ci/tasks/test.yml

- name: deploy
  plan:
  - get: cli-plugin-repo
    passed: [test]
    trigger: true
  - put: cli-plugin-repo-pws
    params:
      manifest: cli-plugin-repo/manifest.yml
      path: cli-plugin-repo
      current_app_name: plugins
    on_failure:
       put: slack-alert
       params:
         channel: '#cli-eng'
         text: "@cli-team - ALERT: deploying cli-plugin-repo failed :("
  - put: cf-cli-tracker
    params:
      repos:
      - cli-plugin-repo
