name: "Unit Tests"

on:
  pull_request:
    branches:
    - main
permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Running Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.3'

      - name: Setup test
        run: |
          go install github.com/onsi/ginkgo/v2/ginkgo

      - name: Run Tests
        run: |
          export GOPATH=$HOME/cli-plugin-repo
          export PATH=$GOPATH/bin:$PATH
          bin/test
    env:
      BINARY_VALIDATION: false

