// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/cli-plugin-repo/models"
	"github.com/cloudfoundry-incubator/cli-plugin-repo/parser"
)

type FakeYamlParser struct {
	ParseStub        func() ([]models.Plugin, error)
	parseMutex       sync.RWMutex
	parseArgsForCall []struct{}
	parseReturns struct {
		result1 []models.Plugin
		result2 error
	}
}

func (fake *FakeYamlParser) Parse() ([]models.Plugin, error) {
	fake.parseMutex.Lock()
	defer fake.parseMutex.Unlock()
	fake.parseArgsForCall = append(fake.parseArgsForCall, struct{}{})
	if fake.ParseStub != nil {
		return fake.ParseStub()
	} else {
		return fake.parseReturns.result1, fake.parseReturns.result2
	}
}

func (fake *FakeYamlParser) ParseCallCount() int {
	fake.parseMutex.RLock()
	defer fake.parseMutex.RUnlock()
	return len(fake.parseArgsForCall)
}

func (fake *FakeYamlParser) ParseReturns(result1 []models.Plugin, result2 error) {
	fake.ParseStub = nil
	fake.parseReturns = struct {
		result1 []models.Plugin
		result2 error
	}{result1, result2}
}

var _ parser.YamlParser = new(FakeYamlParser)
